name: Build Mod

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Install Gradle 2.14.1
      run: |
        wget https://services.gradle.org/distributions/gradle-2.14.1-bin.zip
        unzip -q gradle-2.14.1-bin.zip
        echo "$PWD/gradle-2.14.1/bin" >> $GITHUB_PATH

    - name: Build Mod
      run: gradle build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GCBlockHit-Mod
        path: build/libs/*.jar
